on:
  pull_request:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'

name: "Test"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  coveritup:
    strategy:
      matrix:
        go-version: [latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: kevincobain2000/action-gobrew@v2
        with:
          version: ${{ matrix.go-version }}


      - name: Install Tools
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest


      - run: go mod tidy
      - run: go build main.go
      - run: go test -race -v ./...
      - run: golangci-lint run ./...
